### ISSUE TITLE
file with and without extension

### ISSUE THREAD

**Issue by grylem** [brinsche/QLSyntax#1]
Hi,
with some files I have a strange situation
echo test >test
QLSyntax works fine
echo test >test.test
QLSyntax does not work

P.S.
If you have time please add Light/Dark support.

**Comment by brinsche** [comment]
Filetype support is somewhat complicated, if you run `mdls -name kMDItemContentType file` you get the Uniform Type Identifier for that file but supported UTIs have to be declared in the plugin like this: https://github.com/brinsche/QLSyntax/blob/master/QLSyntaxPlugin/Info.plist#L31 as far as I know, so supporting arbitrary may be impossible

do you mean automatic light/dark support? setting a custom theme should work already

**Comment by grylem** [comment]
in both cases uti's have public.data and your old QLSyntaxHighlight shows the contents of files on High Sierra. But anyway, thanks for the clarification

> do you mean automatic light/dark support?

Of course. With different themes for light/dark.

**Comment by brinsche** [comment]
Hm, weird. Maybe I'll have time to look into that on the weekend, thanks for the report

**Comment by grylem** [comment]
Didn't you find time?

**Comment by brinsche** [comment]
Not yet sorry, but I may have longer weekends soon and I ordered a new macbook for additional motivation

**Comment by grylem** [comment]
It will be great.

**Comment by brinsche** [comment]
I've pushed a new version with a second setting for the dark theme and dark/light mode detection when highlighting.
You might need to run `rustup target add aarch64-apple-darwin` to build it, because the rust library will be compiled for both architectures at the moment.

I'll look into files without extensions and improving the UI later

**Comment by grylem** [comment]
Thanks.

**Comment by grylem** [comment]
Is there any progress?

**Comment by brinsche** [comment]
Sorry I kinda forgot about this, but I just tried your example and for my the kMDItemContentType changes with the file extension, I don't know if I can do much about that

```
$ echo test > test                       
$ mdls -name kMDItemContentType test     
kMDItemContentType = "public.data"
$ echo test > test.test                  
$ mdls -name kMDItemContentType test.test
kMDItemContentType = "dyn.ah62d4rv4ge81k3pxsu"
```
